### ISSUE TITLE
First Issue 

### ISSUE THREAD

**Issue by vmtzgr** [LernMoment/einstieg-csharp.LernMoment.de#1]
Hello Issue

**Comment by suchja** [comment]
@FSN579 Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Leider hast du ein Repository erwischt auf das ich nicht so häufig schaue. Daher habe ich es erst jetzt gesehen 😔.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by ChristianNeumann0708** [comment]
Hallo Jan,
auch für mich ist GitHub ganz neu. Ich finde es noch recht unübersichtlich und versuche erstmal mich zurecht zu finden.

Gruß Christian
